x-dls-variables: &dls-variables
  TZ: Europe/Moscow
  DLS_URL: 176.124.211.156
  ADMIN_USERNAME: "super_admin"
  ADMIN_PASSWORD: "super_password"
  DLS_PORT: 8080
  LEASE_EXPIRE_DAYS: 1
  DATABASE: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}
  DEBUG: false
  VERSION: 1.0

services:
  dls:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always

    environment:
      <<: *dls-variables
    ports:
      - "8080:8080"
    volumes:
      - /opt/docker/fastapi-dls/cert:/app/cert
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
